Photo upload
maximumJavascript/firebase-study pull request #14
Opened 2023-02-21 15:51 UTC by Alextwixmen

добавил возможность прикрепления фотки к посту

2023-02-22 10:10 UTC, Polotenhicko reviewed
форматирование съехало, надо бы его сделать

2023-02-22 11:55 UTC, Alextwixmen commented on src/home/PostItem/PostItem.js
> +      {imgJsx}
Да, я не сделал npm install, поэтому и были проблемы с форматированием из-за новых изменений, которых у меня не было в притере

2023-02-25 12:49 UTC, Polotenhicko requested changes
Сделать про `jsx` и норм

2023-02-25 13:18 UTC, Polotenhicko approved these changes

2023-02-25 13:18 UTC, Polotenhicko commented on src/home/PostItem/PostItem.js
> +  let src = props.post.base64Img;
максимальный nit: константа, Саша, константа

2023-02-25 18:00 UTC, merged