Button and dropdown
maximumJavascript/firebase-study pull request #15
Opened 2023-02-22 09:34 UTC by Igorsml

в src добавил sandbox, где разделил по папкам кнопку и дропдаун. 
Компоненты с заглавной указал, использовал модульный css. 
Кнопка на базовых css (hover, active)
Конфликты решал в IDE после мержа с мастер.
Приложена помощь Артёма как босса качалки

2023-02-22 16:16 UTC, maximumJavascript approved these changes

2023-02-25 12:58 UTC, Polotenhicko requested changes

2023-02-25 12:58 UTC, Polotenhicko commented on src/sandbox/button/button.js
> +    );
Как говорил Макс, компонент button не должен содержать лишнее, должна быть сама кнопка

2023-02-25 12:58 UTC, Polotenhicko commented on src/sandbox/dropdown/dropdown.js
> +            <Icon />
nit: название поконкретнее, а то непонятно что за иконка

2023-02-25 12:58 UTC, Polotenhicko commented on src/sandbox/dropdown/dropdown.js
> +              {optionsList.map((option) => (
Снова, как говорил Макс, нам нужно принимать в виде пропсов этот список, чтобы можно было свой список кинуть

2023-02-27 12:29 UTC, Igorsml commented on src/sandbox/dropdown/dropdown.js
> +              {optionsList.map((option) => (
Спасибо, я бревно, хз как показать что исправил, показываю так

[link на файл](src/sandbox/dropdown/dropdown.js)

![image](https://user-images.githubusercontent.com/75610081/221563757-2b867712-fd08-4c4e-a5db-665e5a0c692a.png)

2023-02-27 12:29 UTC, Igorsml commented on src/sandbox/dropdown/dropdown.js
> +              {optionsList.map((option) => (
Спасибо, я бревно, хз как показать что исправил, показываю так

[link на файл](src/sandbox/dropdown/dropdown.js)

![image](https://user-images.githubusercontent.com/75610081/221563757-2b867712-fd08-4c4e-a5db-665e5a0c692a.png)

2023-02-27 12:31 UTC, Igorsml commented on src/sandbox/button/button.js
> +    );
Укоротил, не уверен что defaultProps нужны, но где-то подсмотрел что используется

[link](src/sandbox/button/button.js)

2023-02-27 12:38 UTC, Polotenhicko approved these changes

2023-02-27 14:25 UTC, merged