рефакторинг
maximumJavascript/firebase-study pull request #21
Opened 2023-03-03 12:35 UTC by Alextwixmen

переписал на класс постайтем(синк), добавл проверку на зареганого юзера, удалил лишние файлы и неиспользумый код

2023-03-03 14:00 UTC, Polotenhicko requested changes

2023-03-03 14:00 UTC, Polotenhicko commented on src/viewsCounter/ViewsCounter.js
>      });
uid текущего авторизированного пользователя можно взять из auth
вот пример https://github.com/maximumJavascript/firebase-study/blob/viewsCounter/src/comments/CreateComment/createComment.service.js

2023-03-03 14:00 UTC, Polotenhicko commented on src/viewsCounter/ViewsCounter.js
>    arrWithRefs = (arr) => {
не понятно по имени что делает метод

2023-03-03 14:00 UTC, Polotenhicko commented on src/viewsCounter/ViewsCounter.js
>      let observer = new IntersectionObserver(this.consolidateInfo, this.options);
nit: const

2023-03-03 14:00 UTC, Polotenhicko commented on src/home/PostItem/PostItem.js
> +      <div className={styles.post} postid={props.post.id} ref={this.ref}>
если делаем кастомный атрибут, то для этого есть dataset

2023-03-03 14:01 UTC, Polotenhicko commented on src/viewsCounter/ViewsCounter.js
>      });
```
this.updateInfo(
          storageService.getUserIdFromStorage(),
          post.target.getAttribute('postid')
        );
```

2023-03-03 15:05 UTC, Alextwixmen commented on src/viewsCounter/ViewsCounter.js
>      });
Спасибо, сделал так

2023-03-03 15:05 UTC, Alextwixmen commented on src/viewsCounter/ViewsCounter.js
>    arrWithRefs = (arr) => {
поменял название

2023-03-03 15:05 UTC, Alextwixmen commented on src/viewsCounter/ViewsCounter.js
>      let observer = new IntersectionObserver(this.consolidateInfo, this.options);
ну хоть не var

2023-03-03 15:12 UTC, Polotenhicko commented on src/viewsCounter/ViewsCounter.js
>      });
Если оставить, то чел может в localstorage поменять свой айди и сделать накрутку, либо от лица другого пользователя что-то сделать

2023-03-03 15:26 UTC, Alextwixmen commented on src/home/PostItem/PostItem.js
> +      <div className={styles.post} postid={props.post.id} ref={this.ref}>
![image](https://user-images.githubusercontent.com/104777630/222759507-12d459be-58b7-42ed-a522-3fd87cdacc4f.png)

2023-03-03 17:15 UTC, Polotenhicko commented on src/home/PostItem/PostItem.js
> +      <div className={styles.post} postid={props.post.id} ref={this.ref}>
![image](https://user-images.githubusercontent.com/38659418/222782231-4d19fc98-18ee-4d74-aca7-895195f0d510.png)

В доке описано что в 16 версии появилась поддержка кастомных атрибутов, а именно, что стали пропускать их. Но всё также пишут что для кастомных лучше подойдёт data атрибут

2023-03-03 17:16 UTC, Polotenhicko commented on src/home/PostItem/PostItem.js
> +      <div className={styles.post} postid={props.post.id} ref={this.ref}>
![image](https://user-images.githubusercontent.com/38659418/222785109-46f18988-3494-4be0-9bf4-d039f7acf713.png)

2023-03-03 17:26 UTC, Polotenhicko commented
Вроде ещё с синка где-то было `if (...) {return...} else {return...}`

2023-03-16 14:44 UTC, Igorsml approved these changes
Лить, фиксить конфликты

2023-03-16 19:19 UTC, Polotenhicko approved these changes

2023-03-17 09:41 UTC, merged