Delete post item
maximumJavascript/firebase-study pull request #22
Opened 2023-03-06 10:51 UTC by Alextwixmen

Тестовая версия удаления постов. Пока что не совсем производительно, нужно переделать еще.

2023-03-10 08:47 UTC, Igorsml commented on src/comments/PostComments/PostComments.js
>            className={`${homeStyles.container} ${homeStyles.home} ${styles.commentsWrap}`}
На усмотрение: можно юзать classnames 
https://habr.com/en/post/649381/

2023-03-10 08:59 UTC, Igorsml commented on src/home/PostItem/PostItem.js
> +            <button onClick={() => this.props.deletePostItem(props.post.id)}>DEL</button>
О, еще кнопочка, тогда как заработает я на компонент заменю

2023-03-10 09:39 UTC, Igorsml commented on src/viewsCounter/ViewsCounter.js
> +    for (let element of arr) {
NIT: перед for и между методами updateInfo, consolidateInfo и makePostsObservable enter'ов бы налупить чтоб не слипалось)
Также отступ после импортов, но вроде об этом уже Макс говорил

2023-03-10 09:41 UTC, Igorsml approved these changes
Комментарии оставил с пожеланиями

2023-03-10 18:33 UTC, Polotenhicko reviewed
добавь label что нужно ревью как только закончишь

2023-03-17 11:14 UTC, Polotenhicko requested changes

2023-03-17 11:14 UTC, Polotenhicko commented on src/auth/auth.service.js
>            userService.handleAddUsers(value.user);
Возможно будет лучше если мы будет всегда при регистрации добавлять юзера. Вместо добавления нового документа, у нас будет обновлён (или перезаписан) существующий. Это будет решать проблему если у человека поменяются какие-то данные, имя, почта, или ник.

Как рефакторинг этих срок: мы можешь сделать самовызывающуюся функцию `(async ()=> {})()`, так обычно понятнее что мы тут хотим использовать await. Но будет лучше если весь handleLogin сделать async.

2023-03-17 11:14 UTC, Polotenhicko commented on src/comments/PostComments/PostComments.js
>            className={`${homeStyles.container} ${homeStyles.home} ${styles.commentsWrap}`}
У нас уже в package.json установлен classnames, так что в таких случаях приоритетнее его юзать

2023-03-17 11:14 UTC, Polotenhicko commented on src/usersService/UserService.js
можно форматирование сделать как отдельным пр`ом, т.к. остаются всё равно файлы с мёртвым кодом и без отступов

2023-03-17 18:58 UTC, Polotenhicko approved these changes

2023-03-27 15:15 UTC, merged